fixes

diff --git a/build b/build
--- a/build
+++ b/build
@@ -18,191 +18,214 @@ RED=$'\033[01;31m'
 RST=$'\033[0m'
 YLW=$'\033[01;33m'
 
-function banner() {
+function START_SCRIPT() {
+if [[ ${BUILDING_ON_CI} = 'y' ]]; then
+        args="${*}"
+        while [[ ${#} -ge 1 ]]; do
+	case "${1}" in
+                "-b"|"--build")
+                        BUILD=y
+                        ;;
+		"-c"|"--clean")
+			CLEAN=y
+			;;
+                "-h"|"--help")
+                        HELP=y
+                        ;;
+		*)
+			echo "${RED}Opps:Invalid Option${RST}"
+                        exit 1;
+			;;
+		esac
+		shift
+        done
+else
+        echo "${GRN} Welcome ${RST}"
+        read -rsn1 -p "${PURP}Type h for help (b|c|h):${RST}" O
+	case "${O}" in
+                "b"|"build")
+                        BUILD=y
+                        ;;
+		"c"|"clean")
+			CLEAN=y
+			;;
+                "h"|"help")
+                        HELP=y
+                        ;;
+		*)
+			echo "${RED}Opps:Invalid Option${RST}"
+                        exit 1;
+			;;
+		esac
+		shift
+fi
+}
+
+function BANNER() {
 clear
-echo -e "${BLD}${CYN} MADE BY YUVRAJ SAXENA (AKA: frap130)"
-echo
-echo -e "${GRN}================================================================================================"
-echo
-echo -e "${BLD}${ORNG}"
-echo -e "${BLD}${ORNG}                       88   eeee  eeeeee"
-echo -e "${BLD}${ORNG}eeee eeeee  eeeee eeeee 8      8  8    8"
-echo -e "${BLD}${ORNG}8    8   8  8   8 8   8 8      8  8    8"
-echo -e "${BLD}${ORNG}8eee 8eee8e 8eee8 8eee8 8   eee8  8    8"
-echo -e "${BLD}${ORNG}88   88   8 88  8 88   8888    88 8    8"
-echo -e "${BLD}${ORNG}88   88   8 88  8 88   8888 eee88 8eeee8"
-echo
-echo -e "${PURP}================================================================================================"
-echo
-sleep 1
+        echo "${BLD}${CYN} MADE BY YUVRAJ SAXENA (AKA: frap130)"
+        echo
+        echo "${GRN}================================================================================================"
+        echo
+        echo "${BLD}${ORNG}"
+        echo "${BLD}${ORNG}                       88   eeee  eeeeee"
+        echo "${BLD}${ORNG}eeee eeeee  eeeee eeeee 8      8  8    8"
+        echo "${BLD}${ORNG}8    8   8  8   8 8   8 8      8  8    8"
+        echo "${BLD}${ORNG}8eee 8eee8e 8eee8 8eee8 8   eee8  8    8"
+        echo "${BLD}${ORNG}88   88   8 88  8 88   8888    88 8    8"
+        echo "${BLD}${ORNG}88   88   8 88  8 88   8888 eee88 8eeee8"
+        echo
+        echo "${PURP}================================================================================================"
+        echo
+        sleep 0.5
 clear
 }
 
 function BINFO() {
-   BNAME="YUVRAJ SAXENA"
-   BNICK="frap130"
-   echo -e "${BLD}${CYN} MADE BY ${BNAME} (AKA: ${BNICK})"
-   export KBUILD_BUILD_USER=Yuvraj
-   export KBUILD_BUILD_HOST=∆Thestral
+        BNAME="YUVRAJ SAXENA"
+        BNICK="frap130"
+        echo "${BLD}${CYN} MADE BY ${BNAME} (AKA: ${BNICK})"
+        export KBUILD_BUILD_USER=Yuvraj
+        export KBUILD_BUILD_HOST=∆Thestral
 }
 
 function TOOLCHAIN() {
 if [[ ! -d linaro ]];
 then
-    echo -e "${RED}####################################"
-    echo -e "${CYN}#       TOOLCHAIN NOT FOUND!       #"
-    echo -e "${YLW}####################################"
+        echo "${RED}####################################"
+        echo "${CYN}#       TOOLCHAIN NOT FOUND!       #"
+        echo "${YLW}####################################"
 clear
-    echo -e "${YLW}####################################"
-    echo -e "${GRN}#       CLONING TOOLCHAIN          #"
-    echo -e "####################################"
-    git clone -q https://github.com/frap130/linaro-5.5.0.git linaro
-    export ARCH=arm CROSS_COMPILE=$PWD/linaro/bin/arm-linux-gnueabi-
+        echo "${YLW}####################################"
+        echo "${GRN}#       CLONING TOOLCHAIN          #"
+        echo "####################################"
+        git clone -q https://github.com/frap130/linaro-5.5.0.git linaro
+        export ARCH=arm CROSS_COMPILE=$PWD/linaro/bin/arm-linux-gnueabi-
 else
-    export ARCH=arm CROSS_COMPILE=$PWD/linaro/bin/arm-linux-gnueabi-
+        export ARCH=arm CROSS_COMPILE=$PWD/linaro/bin/arm-linux-gnueabi-
 fi
 }
 
 function BUILD() {
-    mkdir -p out
-    echo -e "${PURP} READING DEFCONFIG..."
-    make z5lte_defconfig O=out/ &>> defconfig.log
+        mkdir -p out
+        echo "${PURP} READING DEFCONFIG..."
+        make z5lte_defconfig O=out/ &>> defconfig.log
 clear
-    echo -e "${YLW} BUILDING KERNEL..." 
-    make -j4 O=out/ &>> Kernel.log
-    KIMAGE=out/arch/arm/boot/zImage-dtb
-}
-
-function transfer() {
-    file="$1"
-    zipname=$(echo "${file}" | awk -F '/' '{print $NF}')
-    destination="$2"
-    url=$(curl -# -T "${file}" https://transfer.sh/${destination})
-    printf '\n'
-    echo -e "Download $zipname at $url"
-}
-
-function format_time() {
-    MINS=$(((${1}-${2})/60))
-    SECS=$(((${1}-${2})%60))
-    if [[ ${MINS} -ge 60 ]]; then
-        HOURS=$((${MINS}/60))
-        MINS=$((${MINS}%60))
-    fi
-
-    if [[ ${HOURS} -eq 1 ]]; then
-        TIME_STRING+="1 HOUR, "
-    elif [[ ${HOURS} -ge 2 ]]; then
-        TIME_STRING+="${HOURS} HOURS, "
-    fi
-
-    if [[ ${MINS} -eq 1 ]]; then
-        TIME_STRING+="1 MINUTE"
-    else
-        TIME_STRING+="${MINS} MINUTES"
-    fi
-
-    if [[ ${SECS} -eq 1 && -n ${HOURS} ]]; then
-        TIME_STRING+=", AND 1 SECOND"
-    elif [[ ${SECS} -eq 1 && -z ${HOURS} ]]; then
-        TIME_STRING+=" AND 1 SECOND"
-    elif [[ ${SECS} -ne 1 && -n ${HOURS} ]]; then
-        TIME_STRING+=", AND ${SECS} SECONDS"
-    elif [[ ${SECS} -ne 1 && -z ${HOURS} ]]; then
-        TIME_STRING+=" AND ${SECS} SECONDS"
-    fi
-
-    echo ${TIME_STRING}
+        echo "${YLW} BUILDING KERNEL..." 
+        make -j4 O=out/ &>> Kernel.log
+        OIMAGE=out/arch/arm/boot/zImage-dtb
 }
 
 function CHECK() {
-if [[ ! -e ${KIMAGE} ]];
-then
-    echo -e "${RED}############################"
-    echo -e "${RED}#        BUILD ERROR!      #"
-    echo -e "${RED}############################"
-    echo -e "${CYN}#       Uploading Logs     #"
-    echo -e "${RED}############################"
-    clear
-    transfer Kernel.log
-else
-    echo -e "${GRN} #####################################"
-    echo -e "${GRN} #                                   #"
-    echo -e "${GRN} #  SUCCESSFULLY BUILDED KERNEL      #"
-    echo -e "${GRN} #        -BY FRAP130                #"
-    echo -e "${GRN} #                                   #"
-    echo -e "${GRN} #####################################"
-    echo -e "${ORNG} #  uploading Kernel                #"
-    echo -e "${ORNG} #####################################"
-    mv ${KIMAGE} Kernel
-    zip -r Kernel.zip Kernel
 clear
-    transfer Kernel.zip
+if [[ ! -e ${OIMAGE} ]];
+then
+        echo "${RED}############################"
+        echo "${RED}#        BUILD ERROR!      #"
+        echo "${RED}############################"
+        echo "${CYN}#       Uploading Logs     #"
+        echo "${RED}############################"
+clear
+        TRANSFER Kernel.log
+else
+        echo "${GRN} #####################################"
+        echo "${GRN} #                                   #"
+        echo "${GRN} #  SUCCESSFULLY BUILDED KERNEL      #"
+        echo "${GRN} #        -BY FRAP130                #"
+        echo "${GRN} #                                   #"
+        echo "${GRN} #####################################"
+        echo "${ORNG} #  uploading Kernel                #"
+        echo "${ORNG} #####################################"
+        mv ${OIMAGE} Kernel
+        zip -r Kernel.zip Kernel
+clear
+        TRANSFER Kernel.zip
 fi
 }
 
 function CLEAN() {
 clear
-    echo -e "${GRN}#        Cleaning Tree!      #"
-    make clean >/dev/null
-    make mrproper >/dev/null
+        echo "${GRN}#        Cleaning Tree!      ${RST}"
+        make clean >/dev/null
+        make mrproper >/dev/null
 clear
 }
 
 function HELP() {
-	echo -e "${YLW}options:"
-	echo -e "${YLW}  -h, --help     display this help message"
-	echo -e "${YLW}  -c, --clean    clean tree before building"
-	echo -e "${YLW}  -b, --build    build Kernel"
+	echo "${ORNG}options:${RST}"
+	echo "${CYN}  b, build     Build Kernel${RST}"
+	echo "${RST}  c, clean     clean Kernel${RST}"
+	echo "${GRN}  h, Help      Options${RST}"
         read junk
 }
 
-function PARAMS() {
-params="${*}"
-while [[ ${#} -ge 1 ]]; do
-	case ${1} in
-		"-h"|"--help")
-			Help=y
-			;;
-		"-c"|"--clean")
-			CLEAN_TREE=y
-			;;
-		"-b"|"--build")
-			BUILD_KERNEL=y
-			;;
-		*)
-			echo -e "${RED}warning: not enough parameters specified"
-			;;
-		esac
-		shift
-done
+function TRANSFER() {
+        file="$1"
+        zipname=$(echo "${file}" | awk -F '/' '{print $NF}')
+        destination="$2"
+        url=$(curl -# -T "${file}" https://transfer.sh/${destination})
+        printf '\n'
+        echo "Download $zipname at $url"
 }
 
-PARAMS "${@}"
-
-if [[ "${BUILD_KERNEL}" = 'y' ]]; then
-clear
-banner
-clear
-START=$(date +"%s")
-TOOLCHAIN
-clear
-sleep 0.5
-BINFO
-sleep 0.5
-BUILD
-CHECK
-END=$(date +%s)
-TIME_STRING="$(format_time "${START}" "${END}")"
-echo -e "${GRN}Completed In: ${TIME_STRING}"
+function FORMAT_TIME() {
+        MINS=$(((${1}-${2})/60))
+        SECS=$(((${1}-${2})%60))
+if [[ ${MINS} -ge 60 ]]; then
+        HOURS=$((${MINS}/60))
+        MINS=$((${MINS}%60))
 fi
 
-if [[ "${CLEAN_TREE}" = 'y' ]]; then
-clear
-CLEAN
+if [[ ${HOURS} -eq 1 ]]; then
+        TIME_STRING+="1 HOUR, "
+elif [[ ${HOURS} -ge 2 ]]; then
+        TIME_STRING+="${HOURS} HOURS, "
 fi
 
-if [[ "${Help}" = 'y' ]]; then
+if [[ ${MINS} -eq 1 ]]; then
+        TIME_STRING+="1 MINUTE"
+else
+        TIME_STRING+="${MINS} MINUTES"
+fi
+
+if [[ ${SECS} -eq 1 && -n ${HOURS} ]]; then
+        TIME_STRING+=", AND 1 SECOND"
+elif [[ ${SECS} -eq 1 && -z ${HOURS} ]]; then
+        TIME_STRING+=" AND 1 SECOND"
+elif [[ ${SECS} -ne 1 && -n ${HOURS} ]]; then
+        TIME_STRING+=", AND ${SECS} SECONDS"
+elif [[ ${SECS} -ne 1 && -z ${HOURS} ]]; then
+        TIME_STRING+=" AND ${SECS} SECONDS"
+fi
+
+        echo ${TIME_STRING}
+}
+
+        BANNER
+
+if [[ ${BUILDING_ON_CI} = 'y' ]]; then
+        START_SCRIPT "${@}"
+else
+	START_SCRIPT
+fi
+
+if [[ "${BUILD}" = 'y' ]]; then
 clear
-HELP
+        START=$(date +"%s")
+        TOOLCHAIN
+clear
+        BINFO
+        sleep 0.3
+        BUILD
+        CHECK
+        END=$(date +%s)
+        TIME_STRING="$(FORMAT_TIME "${START}" "${END}")"
+        echo "${GRN}Completed In: ${TIME_STRING}"
+elif [[ "${CLEAN}" = 'y' ]]; then
+        CLEAN
+else
+if [[ "${HELP}" = 'y' ]]; then
+clear
+        HELP
+fi
 fi
